---
title: "Monocle3 Basics"
author: "Cole Trapnell"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(monocle3)
library(ggplot2)
```

```{r}
load("~/Desktop/pd")
load("~/Desktop/fd")
load("~/Desktop/expr")

pd <- new("AnnotatedDataFrame", data = pd)
fd <- new("AnnotatedDataFrame", data = fd)
cds <- new_cell_data_set(expr, phenoData = pd, featureData = fd)
```


```{r}
pData(cds)$cell_type2 <- plyr::revalue(as.character(pData(cds)$cluster),
                                        c("1" = 'Erythrocyte',
                                        "2" = 'Erythrocyte',
                                        "3" = 'Erythrocyte',
                                        "4" = 'Erythrocyte',
                                        "5" = 'Erythrocyte',
                                        "6" = 'Erythrocyte',
                                        "7" = 'Multipotent progenitors',
                                        "8" = 'Megakaryocytes',
                                        "9" = 'GMP',
                                        "10" = 'GMP',
                                        "11" = 'Dendritic cells',
                                        "12" = 'Basophils',
                                        "13" = 'Basophils',
                                        "14" = 'Monocytes',
                                        "15" = 'Monocytes',
                                        "16" = 'Neutrophils',
                                        "17" = 'Neutrophils',
                                        "18" = 'Eosinophls',
                                        "19" = 'lymphoid'))

cell_type_color <- c("Basophils" = "#E088B8",
                    "Dendritic cells" = "#46C7EF",
                    "Eosinophls" = "#EFAD1E",
                    "Erythrocyte" = "#8CB3DF",
                    "Monocytes" = "#53C0AD",
                    "Multipotent progenitors" = "#4EB859",
                    "GMP" = "#D097C4",
                    "Megakaryocytes" = "#ACC436",
                    "Neutrophils" = "#F5918A",
                    'NA' = '#000080')
```

```{r}
# Pass TRUE if you want to see progress output on some of Monocle 3's operations
DelayedArray:::set_verbose_block_processing(TRUE)

# Passing a higher value will make some computations faster but use more memory. Adjust with caution!
options(DelayedArray.block.size=1000e6)

cds <- estimate_size_factors(cds)
cds <- estimate_dispersions(cds)
```

```{r}
cds <- preprocess_cds(cds, num_dim = 20)
```

```{r}
cds <- reduce_dimension(cds, reduction_method = 'UMAP')
```


```{r}
cds <- partition_cells(cds)
```

```{r}
cds <- learn_graph(cds)
```

```{r}
plot_cell_trajectory(cds,
                     color_by = "cell_type2") +
                     ggplot2::scale_color_manual(values = cell_type_color)
```


```{r}
# a helper function to identify the root principal points:
get_correct_root_state <- function(cds, cell_phenotype, root_type){
  cell_ids <- which(pData(cds)[, cell_phenotype] == root_type)

  closest_vertex <-
    cds@aux_ordering_data[[cds@rge_method]]$pr_graph_cell_proj_closest_vertex
  closest_vertex <- as.matrix(closest_vertex[colnames(cds), ])
  root_pr_nodes <-
    igraph::V(cds@principal_graph)$name[as.numeric(names
      (which.max(table(closest_vertex[cell_ids,]))))]

  root_pr_nodes
}
```

```{r}
MPP_node_ids = get_correct_root_state(cds,
                                      cell_phenotype =
                                        'cell_type2', "Multipotent progenitors")
cds <- order_cells(cds, root_pr_nodes = MPP_node_ids)
plot_cell_trajectory(cds)
```


```{r}
cds <- reduce_dimension(cds, max_components = 3,
                       reduction_method = 'UMAP',
                       metric="cosine",
                       verbose = F)

cds <- partition_cells(cds)
 
cds <- learn_graph(cds,
                   max_components = 3,
                   RGE_method = 'SimplePPT',
                   partition_component = T,
                   verbose = F)

 cds <- order_cells(cds,
                   root_pr_nodes =
                     get_correct_root_state(cds,
                                            cell_phenotype = 'cell_type2',
                                            "Multipotent progenitors"))
 
 plot_3d_cell_trajectory(cds,
                         color_by="cell_type2",
                         webGL_filename=
                           paste(getwd(), "/trajectory_3D.html", sep=""),
                         palette=cell_type_color,
                         show_backbone=TRUE,
                         useNULL_GLdev=TRUE)
```


```{r}
pr_graph_test <- principal_graph_test(cds, k=3, cores=1)
```

```{r}
 plot_3d_cell_trajectory(cds, markers = c('Hbb-b1'),
                         webGL_filename=paste(getwd(), "/beta_globin.html", sep=""),
                         show_backbone=TRUE,
                         useNULL_GLdev=TRUE)
```

```{r}
   MCA <- readRDS(gzcon(url("http://trapnell-lab.gs.washington.edu/public_share/MCA_merged_mat.rds")))
    cell.meta.data <- read.csv(url("http://trapnell-lab.gs.washington.edu/public_share/MCA_All-batch-removed-assignments.csv"), row.names = 1)

overlapping_cells <- intersect(row.names(cell.meta.data), colnames(MCA))
gene_ann <- data.frame(gene_short_name = row.names(MCA), row.names = row.names(MCA))

pd <- new("AnnotatedDataFrame",data=cell.meta.data[overlapping_cells, ])
fd <- new("AnnotatedDataFrame",data=gene_ann)

MCA_cds <- new_cell_data_set(MCA[, overlapping_cells], phenoData = pd,featureData =fd,
                          expression_family = "negbinomial.size",
                          lower_detection_limit=1)
    
```

```{r}
DelayedArray:::set_verbose_block_processing(TRUE)
options(DelayedArray.block.size=1000e6)
MCA_cds <- estimate_size_factors(MCA_cds)
MCA_cds <- estimate_dispersions(MCA_cds)
```

```{r}
library(dplyr)

disp_table = dispersion_table(MCA_cds)
disp_table = disp_table %>% mutate(excess_disp =
  (dispersion_empirical - dispersion_fit) / dispersion_fit) %>%
    arrange(plyr::desc(excess_disp))
top_subset_genes = as.character(head(disp_table, 2500)$gene_id)

MCA_cds = set_ordering_filter(MCA_cds, top_subset_genes)
MCA_cds <- preprocess_cds(MCA_cds,  method = 'PCA',
                         norm_method = 'log',
                         num_dim = 50,
                         verbose = T)
MCA_cds <- reduce_dimension(MCA_cds, max_components = 2,
                       reduction_method = 'UMAP',
                       metric="correlation",
                       min_dist = 0.75,
                       n_neighbors = 50,
                       verbose = T)
```

```{r}
MCA_cds <- cluster_cells(MCA_cds,
                        method = 'louvain',
                        res = 1e-6,
                        louvain_iter = 1,
                        verbose = T)
    
```

```{r}
col_vector_origin <- c("#db83da",
              "#53c35d",
              "#a546bb",
              "#83b837",
              "#a469e6",
              "#babb3d",
              "#4f66dc",
              "#e68821",
              "#718fe8",
              "#d6ac3e",
              "#7957b4",
              "#468e36",
              "#d347ae",
              "#5dbf8c",
              "#e53e76",
              "#42c9b8",
              "#dd454a",
              "#3bbac6",
              "#d5542c",
              "#59aadc",
              "#cf8b36",
              "#4a61b0",
              "#8b8927",
              "#a24e99",
              "#9cb36a",
              "#ca3e87",
              "#36815b",
              "#b23c4e",
              "#5c702c",
              "#b79add",
              "#a55620",
              "#5076af",
              "#e38f67",
              "#85609c",
              "#caa569",
              "#9b466c",
              "#88692c",
              "#dd81a9",
              "#a35545",
              "#e08083",
              "#17becf",
              "#9edae5")
col_vector <-
  col_vector_origin[1:length(unique(as.character(pData(MCA_cds)$Tissue)))]
names(col_vector) <- unique(as.character(pData(MCA_cds)$Tissue))
options(repr.plot.width = 11)
options(repr.plot.height = 8)
plot_cell_clusters(MCA_cds,
                   color_by = 'Tissue',
                   cell_size = 0.1,
                   show_group_id = T)  +
  theme(legend.text=element_text(size=6)) + #set the size of the text
  theme(legend.position="right") #put the color legend on the right
```



```{r}
options(repr.plot.width = 11)
options(repr.plot.height = 8)
cluster_col_vector <-
  col_vector_origin[1:length(unique(as.character(pData(MCA_cds)$Cluster)))]
names(cluster_col_vector) <- unique(as.character(pData(MCA_cds)$Cluster))
plot_cell_clusters(MCA_cds,
                   color_by = 'Cluster',
                   cell_size = 0.1,
                   show_group_id = T) +
    scale_color_manual(values = cluster_col_vector) +
    theme(legend.text=element_text(size=6)) + #set the size of the text
    theme(legend.position="right") #put the color legend on the right
```



```{r}
Cluster_tissue_stat <- table(pData(MCA_cds)[, c('Cluster', 'Tissue')])

Cluster_tissue_stat <- apply(Cluster_tissue_stat, 1, function(x) x / sum(x))

Cluster_tissue_stat_ordered <- t(Cluster_tissue_stat)

options(repr.plot.width=10, repr.plot.height=7)

order_mat <- t(apply(Cluster_tissue_stat_ordered, 1, order))
max_ind_vec <- c()

for(i in 1:nrow(order_mat)) {
  tmp <- max(which(!(order_mat[i, ] %in% max_ind_vec)))
  max_ind_vec <- c(max_ind_vec, order_mat[i, tmp])
}

max_ind_vec <- max_ind_vec[!is.na(max_ind_vec)]

max_ind_vec <- c(max_ind_vec, setdiff(1:ncol(Cluster_tissue_stat),
                                      max_ind_vec))
Cluster_tissue_stat_ordered <-
  Cluster_tissue_stat_ordered[, row.names(Cluster_tissue_stat)[max_ind_vec]]

pheatmap::pheatmap(Cluster_tissue_stat_ordered,
                   cluster_cols = F,
                   cluster_rows = F,
                   color = colorRampPalette(RColorBrewer::brewer.pal(n=9,
                    name='Greys'))(10))
# annotation_row = annotation_row, annotation_colors = annotation_colors
```


```{r}
Cluster_tissue_stat <- table(pData(MCA_cds)[, c('Cluster', 'Tissue')])

Cluster_tissue_stat <- apply(Cluster_tissue_stat, 2, function(x) x / sum(x))

Cluster_tissue_stat_ordered <- t(Cluster_tissue_stat)

options(repr.plot.width=10, repr.plot.height=7)
order_mat <- t(apply(Cluster_tissue_stat_ordered, 2, order))
max_ind_vec <- c()

for(i in 1:nrow(order_mat)) {
  tmp <- max(which(!(order_mat[i, ] %in% max_ind_vec)))
  max_ind_vec <- c(max_ind_vec, order_mat[i, tmp])
}

max_ind_vec <- max_ind_vec[!is.na(max_ind_vec)]

max_ind_vec <- c(max_ind_vec, setdiff(1:ncol(Cluster_tissue_stat), max_ind_vec))
Cluster_tissue_stat_ordered <-
  Cluster_tissue_stat_ordered[colnames(Cluster_tissue_stat)[max_ind_vec], ]

pheatmap::pheatmap(Cluster_tissue_stat_ordered,
                   cluster_cols = F,
                   cluster_rows = F,
                   color = colorRampPalette(RColorBrewer::brewer.pal(n=9,
                      name='Greys'))(10))
# annotation_row = annotation_row, annotation_colors = annotation_colors
```

```{r}
options(repr.plot.width = 11)
options(repr.plot.height = 8)
MCA_cds_res_resolution <- cluster_cells(MCA_cds,
                                       use_pca = F,
                                       method = 'louvain',
                                       res = 5e-5,
                                       louvain_iter = 1,
                                       verbose = T)
cluster_col_vector <-
  col_vector_origin[1:length(
    unique(as.character(pData(MCA_cds_res_resolution)$Cluster)))]
names(cluster_col_vector) <-
  unique(as.character(pData(MCA_cds_res_resolution)$Cluster))

plot_cell_clusters(MCA_cds_res_resolution,
                   color_by = 'Cluster',
                   cell_size = 0.1,
                   show_group_id = T) +
  theme(legend.text=element_text(size=6)) + #set the size of the text
  theme(legend.position="right") #put the color legend on the right
```

```{r}
options(repr.plot.width = 11)
options(repr.plot.height = 8)
MCA_cds_res_resolution <- cluster_cells(MCA_cds,
                                       use_pca = F,
                                       method = 'louvain',
                                       res = 5e-7,
                                       louvain_iter = 1,
                                       verbose = T)
cluster_col_vector <-
  col_vector_origin[1:length(
    unique(as.character(pData(MCA_cds_res_resolution)$Cluster)))]
names(cluster_col_vector) <-
  unique(as.character(pData(MCA_cds_res_resolution)$Cluster))

plot_cell_clusters(MCA_cds_res_resolution,
                   color_by = 'Cluster',
                   cell_size = 0.1,
                   show_group_id = T) +
  theme(legend.text=element_text(size=6)) + #set the size of the text
  theme(legend.position="right") #put the color legend on the right
```

```{r}
start <- Sys.time()
spatial_res <- principal_graph_test(MCA_cds, relative_expr = TRUE, k = 25, cores = detectCores() - 2, verbose = FALSE)
end <- Sys.time()
end - start
```

```{r}
cluster_marker_res <-
  find_cluster_markers(MCA_cds,
                       spatial_res,
                       group_by = 'Cluster',
                       morans_I_threshold = 0.25)
```

```{r}
genes <- (cluster_marker_res %>%
          dplyr::filter(mean > 0.5, percentage > 0.1) %>%
          dplyr::group_by(Group) %>% dplyr::slice(which.max(specificity)))
options(repr.plot.width=22, repr.plot.height=12)
plot_markers_by_group(MCA_cds, genes$gene_short_name, group_by = 'Cluster', ordering_type = 'maximal_on_diag')
```


```{r}
genes <-
  (cluster_marker_res %>%
  dplyr::filter(mean > 0.5, percentage > 0.1) %>%
  dplyr::group_by(Group) %>%
  dplyr::top_n(5, wt = specificity))
plot_markers_cluster(MCA_cds, as.character(genes$gene_short_name),
                     minimal_cluster_fraction = 0.05)
```


```{r}
options(repr.plot.width=22, repr.plot.height=12)
genes <- cluster_marker_res %>%
         dplyr::filter(mean > 0.5, percentage > 0.1, specificity > 0.7) %>%
         dplyr::group_by(Group) %>%
         dplyr::arrange(Group, dplyr::desc(specificity))
plot_markers_cluster(MCA_cds,
                     as.character(genes$gene_short_name),
                     minimal_cluster_fraction = 0.05,
                     show_rownames = F)
```

```{r}
top_4_genes <- genes %>%
               dplyr::filter(Group == 7) %>%
               dplyr::top_n(n = 4, wt  = specificity)
top_4_genes
```

```{r}
options(repr.plot.width = 8)
options(repr.plot.height = 9)
marker_genes <- top_4_genes$Gene
plot_cell_clusters(MCA_cds,
                   markers = as.character(marker_genes),
                   show_group_id = T, cell_size = 0.1)
```

```{r}
cluster_marker_res %>%
  dplyr::filter(gene_short_name %in% c('Csn3', 'Csn1s1'), Group == 7)
options(repr.plot.width = 8)
options(repr.plot.height = 5.5)
plot_cell_clusters(MCA_cds,
                   markers = c('Csn3', 'Csn1s1'),
                   show_group_id = T, cell_size = 0.1)
```















