#' Methods for the cell_data_set class
#' @name cell_data_set-methods
#' @docType methods
#' @rdname cell_data_set-methods
#' @param object The cell_data_set object
setValidity( "cell_data_set", function( object ) {
  TRUE
} )


#' Set the minimum spanning tree generated by Monocle during cell ordering.
#'
#' Sets the minimum spanning tree used by Monocle during cell ordering. Not intended to be called directly.
#'
#' @param cds A cell_data_set object.
#' @param value an igraph object describing the minimum spanning tree.
#' @return An updated cell_data_set object
#' @export
#' @examples
#' \dontrun{
#' cds <- size_factors(T)
#' }
`size_factors<-` <- function( cds, value ) {
  stopifnot( methods::is( cds, "cell_data_set" ) )
  colData(cds)$Size_Factor <- value
  methods::validObject( cds )
  cds
}

#' Set the minimum spanning tree generated by Monocle during cell ordering.
#'
#' Sets the minimum spanning tree used by Monocle during cell ordering. Not intended to be called directly.
#'
#' @param cds A cell_data_set object.
#' @param value an igraph object describing the minimum spanning tree.
#' @return An updated cell_data_set object
#' @export
#' @examples
#' \dontrun{
#' cds <- size_factors(T)
#' }
size_factors <- function( cds, value ) {
  stopifnot( methods::is( cds, "cell_data_set" ) )
  sf <- colData(cds)$Size_Factor
  names( sf ) <- colnames( counts(cds) )
  sf
}

check_size_factors <- function(cds) {
    if (is.null(size_factors(cds))){
      stop(paste("Error: you must call estimate_size_factors() before calling",
                 "this function."))
    }
    if (sum(is.na(size_factors(cds))) > 0){
      stop("Error: one or more cells has a size factor of NA.")
    }
}

